// api/blog-post.js — server-rendered /blog/[slug] page
// Routed via vercel.json rewrite: /blog/:slug -> /api/blog-post?slug=:slug
import { getServiceClient } from '../lib/supabase.js';
import { getAuthor } from '../lib/authors.js';

const SITE = 'https://mytripmoney.com';

export default async function handler(req, res) {
  const slug = (req.query?.slug || '').toString().toLowerCase().replace(/[^a-z0-9-]/g, '').slice(0, 80);
  if (!slug) {
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store, max-age=0');
    return res.status(404).send(renderNotFound());
  }

  try {
    const supabase = getServiceClient();
    const { data: post } = await supabase
      .from('blog_posts')
      .select('*')
      .eq('slug', slug)
      .eq('status', 'published')
      .maybeSingle();

    if (!post) {
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.status(404).send(renderNotFound());
    }

    // Pull 3 more recent posts for sidebar
    const { data: more } = await supabase
      .from('blog_posts')
      .select('slug, title, category')
      .eq('status', 'published')
      .neq('slug', slug)
      .order('published_at', { ascending: false })
      .limit(4);

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res.status(200).send(renderPost(post, more || []));
  } catch (e) {
    console.error('blog-post error:', e);
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res.status(500).send(renderNotFound());
  }
}

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function fmtDate(d) {
  if (!d) return '';
  try {
    return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  } catch {
    return '';
  }
}

function renderPost(post, more) {
  const author = getAuthor(post.author_slug || 'marcus-chen');
  const title = esc(post.meta_title || post.title);
  const desc = esc(post.meta_desc || post.excerpt || '');
  const url = `${SITE}/blog/${post.slug}`;

  const ldJson = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.meta_desc || post.excerpt || '',
    datePublished: post.published_at,
    dateModified: post.updated_at || post.published_at,
    author: { '@type': 'Person', name: author.name, jobTitle: author.role },
    publisher: { '@type': 'Organization', name: 'MyTripMoney', url: SITE },
    mainEntityOfPage: url,
    url,
    keywords: (post.tags || []).join(', '),
  };

  const moreList = more
    .map(
      (m) => `<li><a href="/blog/${esc(m.slug)}">${esc(m.title)}</a>${m.category ? ` <span class="more-cat">${esc(m.category)}</span>` : ''}</li>`
    )
    .join('');

  // body_html is generated by Claude — render as-is (trusted internal source)
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${title}</title>
  <meta name="description" content="${desc}">
  <link rel="canonical" href="${url}">
  <meta property="og:title" content="${title}">
  <meta property="og:description" content="${desc}">
  <meta property="og:url" content="${url}">
  <meta property="og:type" content="article">
  <meta property="article:published_time" content="${esc(post.published_at || '')}">
  <meta property="article:author" content="${esc(author.name)}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="icon" type="image/png" href="/favicon.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800;900&family=Sora:wght@600;700;800&display=swap" rel="stylesheet">
  <script type="application/ld+json">${JSON.stringify(ldJson)}</script>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    html, body { background:#0A0F1E; color:#F0F4FF; font-family:'DM Sans',-apple-system,sans-serif; }
    a { color:#00D4FF; }
    .nav { position:sticky; top:0; z-index:10; background:rgba(10,15,30,0.92); backdrop-filter:blur(16px); border-bottom:1px solid #1E2D45; padding:16px 0; }
    .container { max-width:1100px; margin:0 auto; padding:0 24px; }
    .nav-row { display:flex; justify-content:space-between; align-items:center; }
    .logo { font-family:Sora,sans-serif; font-weight:800; font-size:20px; color:#F0F4FF; text-decoration:none; }
    .logo .accent { color:#00D4FF; }
    .nav-links { display:flex; gap:24px; align-items:center; }
    .nav-link { color:#8A9BC4; font-size:14px; font-weight:600; text-decoration:none; }
    .btn { background:#00D4FF; color:#0A0F1E; border:none; border-radius:10px; padding:10px 20px; font-size:14px; font-weight:800; cursor:pointer; text-decoration:none; }
    .layout { display:grid; grid-template-columns:1fr 280px; gap:48px; padding:48px 0 80px; }
    @media (max-width:900px) { .layout { grid-template-columns:1fr; gap:32px; } }
    .crumbs { color:#8A9BC4; font-size:13px; margin-bottom:20px; }
    .crumbs a { color:#8A9BC4; text-decoration:none; }
    .badge { display:inline-block; background:#00D4FF22; color:#00D4FF; font-size:11px; font-weight:700; padding:4px 10px; border-radius:99px; margin-bottom:16px; text-transform:uppercase; letter-spacing:0.5px; }
    h1.post-title { font-family:Sora,sans-serif; font-size:clamp(30px,4vw,44px); font-weight:900; letter-spacing:-1px; line-height:1.15; margin-bottom:20px; color:#F0F4FF; }
    .byline { display:flex; gap:12px; align-items:center; margin-bottom:32px; padding-bottom:24px; border-bottom:1px solid #1E2D45; }
    .avatar { width:44px; height:44px; border-radius:50%; background:#1A2235; border:1px solid #1E2D45; object-fit:cover; display:block; }
    .by-name { font-weight:700; color:#F0F4FF; font-size:14px; }
    .by-role { color:#8A9BC4; font-size:12px; }
    .by-date { color:#4A5880; font-size:13px; margin-left:auto; }
    .body { color:#cbd5e1; font-size:17px; line-height:1.75; }
    .body h2 { font-family:Sora,sans-serif; color:#F0F4FF; font-size:26px; font-weight:800; margin:40px 0 14px; letter-spacing:-0.3px; }
    .body h3 { font-family:Sora,sans-serif; color:#F0F4FF; font-size:20px; font-weight:700; margin:28px 0 10px; }
    .body p { margin:0 0 18px; }
    .body ul, .body ol { margin:0 0 18px 24px; padding:0; }
    .body li { margin-bottom:8px; }
    .body strong { color:#F0F4FF; }
    .body a { color:#00D4FF; text-decoration:underline; text-underline-offset:3px; }
    .body em { color:#a8b6d6; }
    .body blockquote { border-left:3px solid #00D4FF; background:#1A2235; padding:16px 20px; margin:24px 0; color:#cbd5e1; border-radius:0 10px 10px 0; }
    .tags { display:flex; flex-wrap:wrap; gap:8px; margin-top:36px; padding-top:24px; border-top:1px solid #1E2D45; }
    .tag { background:#1A2235; color:#8A9BC4; font-size:12px; font-weight:600; padding:5px 12px; border-radius:99px; border:1px solid #1E2D45; }
    .sidebar { position:sticky; top:88px; align-self:start; }
    .sidebar h3 { font-family:Sora,sans-serif; font-size:14px; font-weight:700; color:#F0F4FF; text-transform:uppercase; letter-spacing:0.8px; margin-bottom:16px; }
    .sidebar ul { list-style:none; padding:0; margin:0; }
    .sidebar li { margin-bottom:14px; line-height:1.4; }
    .sidebar a { color:#F0F4FF; text-decoration:none; font-size:14px; font-weight:600; }
    .sidebar a:hover { color:#00D4FF; }
    .more-cat { color:#4A5880; font-size:11px; font-weight:600; text-transform:uppercase; letter-spacing:0.5px; }
    .cta-card { background:linear-gradient(135deg,#1A2235,#0A0F1E); border:1px solid #00D4FF55; border-radius:14px; padding:24px; margin-top:32px; text-align:center; }
    .cta-card h4 { font-family:Sora,sans-serif; color:#F0F4FF; font-size:16px; font-weight:800; margin-bottom:10px; }
    .cta-card p { color:#8A9BC4; font-size:13px; line-height:1.5; margin-bottom:16px; }
    .footer { border-top:1px solid #1E2D45; padding:40px 0; text-align:center; color:#4A5880; font-size:13px; }
    .footer a { color:#8A9BC4; }
  </style>
</head>
<body>
  <nav class="nav">
    <div class="container nav-row">
      <a href="/" class="logo"><span>My</span><span class="accent">Trip</span><span>Money</span></a>
      <div class="nav-links">
        <a href="/#pricing" class="nav-link">Pricing</a>
        <a href="/blog" class="nav-link">Blog</a>
        <a href="/auth?next=/app" class="btn">Get Started</a>
      </div>
    </div>
  </nav>
  <main class="container">
    <div class="layout">
      <article>
        <div class="crumbs"><a href="/blog">← Back to blog</a></div>
        ${post.category ? `<div class="badge">${esc(post.category)}</div>` : ''}
        <h1 class="post-title">${esc(post.title)}</h1>
        <div class="byline">
          <img class="avatar" src="${esc(author.image)}" alt="${esc(author.name)}" onerror="this.style.display='none'">
          <div>
            <div class="by-name">${esc(author.name)}</div>
            <div class="by-role">${esc(author.role)}</div>
          </div>
          <div class="by-date">${fmtDate(post.published_at)}</div>
        </div>
        <div class="body">${post.body_html || ''}</div>
        ${
          Array.isArray(post.tags) && post.tags.length
            ? `<div class="tags">${post.tags.map((t) => `<span class="tag">${esc(t)}</span>`).join('')}</div>`
            : ''
        }
      </article>
      <aside class="sidebar">
        ${moreList ? `<h3>More articles</h3><ul>${moreList}</ul>` : ''}
        <div class="cta-card">
          <h4>Stop guessing what you're spending abroad.</h4>
          <p>MyTripMoney tracks every dollar, every currency, every leg.</p>
          <a class="btn" href="/auth?next=/app">Start free →</a>
        </div>
      </aside>
    </div>
  </main>
  <footer class="footer">
    <div class="container">© 2026 MyTripMoney · <a href="/">Home</a> · <a href="/#pricing">Pricing</a> · <a href="/blog">Blog</a></div>
  </footer>
</body>
</html>`;
}

function renderNotFound() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Post not found — MyTripMoney</title>
  <meta name="robots" content="noindex">
</head>
<body style="margin:0;background:#0A0F1E;color:#F0F4FF;font-family:system-ui,-apple-system,sans-serif;display:flex;align-items:center;justify-content:center;min-height:100vh;">
  <div style="text-align:center;padding:24px;">
    <div style="font-size:3rem;margin-bottom:12px;">🧭</div>
    <h1 style="font-size:1.5rem;font-weight:800;margin:0 0 12px;">Post not found</h1>
    <p style="color:#8A9BC4;margin:0 0 24px;">We couldn't find that article.</p>
    <a href="/blog" style="display:inline-block;background:#00D4FF;color:#0A0F1E;padding:10px 24px;border-radius:10px;font-weight:800;text-decoration:none;">Back to blog</a>
  </div>
</body>
</html>`;
}
